[[block]]
block = "net"
device = "enp4s0"
interval = 1
format = " $icon: $ip ($speed_down) "
inactive_format = "$icon: down"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "sound"
click = [
  { button = "left", cmd = "pavucontrol" }
]

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"   # or "sway" in swaywm

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%H:%M %d-%m-%Y') "