[[block]]
block = "net"
device = "enp9s0"
interval = 1
format = " $icon: $ip ($speed_down) "
inactive_format = "$icon: down"

[[block]]
block = "memory"
format = " $icon $mem_used / $mem_total "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "amd_gpu"
format = " $icon $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
interval = 5
chip = "k10temp-*"
format = " $icon $average avg "
format_alt = " $icon min - $min, max - $max "


[[block]]
block = "sound"
click = [
  { button = "left", cmd = "pavucontrol" }
]

[[block]]
block = "keyboard_layout"
driver = "sway"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%A %H:%M %d-%m-%Y') "
