[colors.primary]
background = "#242424"
foreground = "#ffffff"

[cursor]
style = "Beam"

[font]
size = 12.5

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 10